version: '3.9'

services:
  # adonis
  aggregator_simulator:
    image: aggsim_image
    container_name: aggregator_simulator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5566:5566"
    env_file:
      - .env
