version: "3.9"

services:
  aggregator_simulator:
    image: mediacartz/aggregator-simulator:1.2.0
    container_name: aggregator_simulator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5566:5566"
    env_file:
      - .env
